# Usage

In [1]:
import os
from dotenv import load_dotenv
from openbb import obb

if 'info' in obb.reference:
    obj = obb.reference["info"]["extensions"]["openbb_provider_extension"]
    print([item for item in obj if "akshare" in item])
    print([item for item in obj if "tushare" in item])
    print([item for item in obj if "tdxquant" in item])

symbols = "601919,600519,000001,00300"
symbols_a = "601919,600519,000001,600325,600028,600036,430047"
symbol_a = "600325"
symbol_hk = "01658"
default_provider = "tdxquant"

os.environ["AKSHARE_API_KEY"] = obb.user.credentials.akshare_api_key.get_secret_value()
os.environ["TUSHARE_API_KEY"] = obb.user.credentials.tushare_api_key.get_secret_value()

#load_dotenv() 
akshare_api_key = os.environ.get("AKSHARE_API_KEY")
if akshare_api_key is None or akshare_api_key == "":
    raise ValueError("AKSHARE_API_KEY environment variable not set.")

tushare_api_key = os.environ.get("TUSHARE_API_KEY")
if tushare_api_key is None or tushare_api_key == "":
    raise ValueError("TUSHARE_API_KEY environment variable not set.")

Extensions to add: akshare@1.2.3
Extensions to remove: akshare@1.2.2

Building...
['akshare@1.2.3']
['tushare@1.2.0']
['tdxquant@1.2.1']

## Equity histrical price

In [3]:
obb.equity.price.historical(symbol="600325", provider=default_provider, use_cache=True, start_date="2026-01-01",end_date="2026-03-08").to_dataframe().tail()

2026-04-23 10:36:58,153 - openbb_tdx.utils.helpers - WARNING - Cache for 600325 is not up-to-date. Last date in cache: 2026-04-21, expected: 2026-04-22.

TQ数据接口初始化成功，使用路径: C:\Users\roger\src\finanalyzer\openbb_tdx\openbb_tdx\utils\helpers.py

2026-04-23 10:37:03,241 - openbb_tdx.utils.helpers - INFO - Getting equity 600325 historical data from cache...

TQ数据连接已关闭

,open,high,low,close,volume,amount,change,change_percent
date,,,,,,,,
2026-03-02,4.27,4.35,4.21,4.29,68826368.0,29469.78,-0.02,-0.464037
2026-03-03,4.30,4.32,4.11,4.14,79248864.0,33189.81,-0.15,-3.496503
2026-03-04,4.10,4.17,4.05,4.09,44675104.0,18344.50,-0.05,-1.207729
2026-03-05,4.13,4.16,4.07,4.10,41824880.0,17121.88,0.01,0.244499
2026-03-06,4.08,4.14,4.07,4.13,39824000.0,16340.81,0.03,0.731707

## Equity Search (股票搜索)

In [4]:
symbol_b="00144"
result = obb.equity.search(query=symbol_b, provider=default_provider).to_dataframe()
result[result['symbol'] == symbol_b]

2026-04-23 10:37:26,616 - openbb_tdx.utils.tdx_equity_search - INFO - Loading symbols from openbb_tdx cache...
2026-04-23 10:37:26,813 - openbb_tdx.models.equity_search - INFO - Searching for 00144 and found 2 results.

  symbol   name exchange
1  00144  招商局港口     HKEX

## Equity Key Metrics

In [ ]:
obb.equity.fundamental.metrics(symbol=symbol_hk, provider=default_provider).to_dataframe().T

TQ数据连接已关闭

                                    0
symbol                          01658
currency                          HKD
market_cap            5262540000000.0
eps                              0.81
price_to_sales          147879.819932
book_value_per_share            10.69
cash_per_share                    0.0
debt_to_equity                    0.0
gross_margin                      1.0
profit_margin                  0.0753
operating_margin                  0.0
return_on_assets             0.004678
return_on_equity             0.075339
dividend_yield                    0.0
enterprise_value      5262540000000.0
ev_to_sales             147879.819932
working_capital                   0.0
ebit_margin                       0.0

## Equity profile

In [7]:
obb.equity.profile(symbol=symbol_hk, use_cache=True, provider=default_provider).to_dataframe().tail()

TQ数据接口初始化成功，使用路径: C:\Users\roger\src\finanalyzer\openbb_tdx\openbb_tdx\models\equity_profile.py

,symbol,name,employees,sector,listed_date,total_assets,total_liabilities,revenue,net_income,shares_outstanding,...,J_mggjj,J_mgjzc2,J_gdqyb,J_gdrs,J_HalfYearFlag,tdx_dycode,rs_hycode_sim,blockzscode,underly_setcode,underly_code
0,01658,邮储银行,12009505,银行,2016-09-28,0.0,116014608.0,35586600.0,8740400.0,0.0,...,0.00,10.69,0.06,0.00,0,-1,108001,882081,0,

## Equity Quote (股票实时报价)

In [2]:
#obb.equity.price.quote(symbols, provider="akshare").to_dataframe().head()
obb.equity.price.quote(symbols, provider="akshare").to_dataframe()[['open', 'high', 'low', 'last_price']].head()

2026-04-23 11:55:59,781 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601919

2026-04-23 11:56:00,492 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600519
2026-04-23 11:56:01,127 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SZ000001
2026-04-23 11:56:01,911 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 00300

      open     high      low  last_price
0    14.43    14.49    14.38       14.41
1  1408.00  1419.70  1405.10     1415.88
2    10.98    11.03    10.93       10.96
3    90.00    90.00    88.60       89.80

## Equity Data

In [3]:
from openbb_app.core.equity_data import EquityData
equity_data = EquityData()

In [4]:
equity_data.get_current_prices(is_realized=True)

2026-04-23 11:41:20,487 - openbb_app.core.equity_data - INFO - Fetching current prices from provider with is_realized=True: 000333,600028,600104,600325,600376,600704,600741,600886,601006,601088,601288,601319,601328,601398,601658,601728,601857,601919,601939,601988
2026-04-23 11:41:20,488 - openbb_app.core.utils - INFO - Fetching quote data for 000333
2026-04-23 11:41:20,494 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SZ000333
2026-04-23 11:41:21,201 - openbb_app.core.utils - INFO - Successfully fetched quote data for 000333
2026-04-23 11:41:21,202 - openbb_app.core.utils - INFO - Fetching quote data for 600028
2026-04-23 11:41:21,208 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600028
2026-04-23 11:41:21,982 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600028
2026-04-23 11:41:21,982 - openbb_app.core.utils - INFO - Fetching quote data for 600104
2026-04-23 11:41:21,988 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600104
2026-04-23 11:41:22,738 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600104
2026-04-23 11:41:22,738 - openbb_app.core.utils - INFO - Fetching quote data for 600325
2026-04-23 11:41:22,743 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600325
2026-04-23 11:41:23,430 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600325
2026-04-23 11:41:23,431 - openbb_app.core.utils - INFO - Fetching quote data for 600376
2026-04-23 11:41:23,437 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600376
2026-04-23 11:41:24,241 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600376
2026-04-23 11:41:24,242 - openbb_app.core.utils - INFO - Fetching quote data for 600704
2026-04-23 11:41:24,247 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600704
2026-04-23 11:41:24,954 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600704
2026-04-23 11:41:24,955 - openbb_app.core.utils - INFO - Fetching quote data for 600741
2026-04-23 11:41:24,960 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600741
2026-04-23 11:41:25,658 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600741
2026-04-23 11:41:25,659 - openbb_app.core.utils - INFO - Fetching quote data for 600886
2026-04-23 11:41:25,664 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600886
2026-04-23 11:41:26,417 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600886
2026-04-23 11:41:26,418 - openbb_app.core.utils - INFO - Fetching quote data for 601006
2026-04-23 11:41:26,423 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601006
2026-04-23 11:41:27,187 - openbb_app.core.utils - INFO - Successfully fetched quote data for 601006
2026-04-23 11:41:27,188 - openbb_app.core.utils - INFO - Fetching quote data for 601088
2026-04-23 11:41:27,192 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601088
2026-04-23 11:41:27,972 - openbb_app.core.utils - INFO - Successfully fetched quote data for 601088
2026-04-23 11:41:27,973 - openbb_app.core.utils - INFO - Fetching quote data for 601288
2026-04-23 11:41:27,978 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601288
2026-04-23 11:41:28,746 - openbb_app.core.utils - INFO - Successfully fetched quote data for 601288
2026-04-23 11:41:28,747 - openbb_app.core.utils - INFO - Fetching quote data for 601319
2026-04-23 11:41:28,752 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601319
2026-04-23 11:41:29,438 - openbb_app.core.utils - INFO - Successfully fetched quote data for 601319
2026-04-23 11:41:29,440 - openbb_app.core.utils - INFO - Fetching quote data for 601328
2026-04-23 11:41:29,445 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601328
2026-04-23 11:41:30,217 - openbb_app.core.utils - INFO - Successfully fetched quote data for 601328
2026-04-23 11:41:30,218 - openbb_app.core.utils - INFO - Fetching quote data for 601398
2026-04-23 11:41:30,224 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601398
2026-04-23 11:41:30,958 - openbb_app.core.utils - INFO - Successfully fetched quote data for 601398
2026-04-23 11:41:30,959 - openbb_app.core.utils - INFO - Fetching quote data for 601658
2026-04-23 11:41:30,964 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601658
2026-04-23 11:41:31,646 - openbb_app.core.utils - INFO - Successfully fetched quote data for 601658
2026-04-23 11:41:31,647 - openbb_app.core.utils - INFO - Fetching quote data for 601728
2026-04-23 11:41:31,653 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601728
2026-04-23 11:41:32,358 - openbb_app.core.utils - INFO - Successfully fetched quote data for 601728
2026-04-23 11:41:32,359 - openbb_app.core.utils - INFO - Fetching quote data for 601857
2026-04-23 11:41:32,365 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601857
2026-04-23 11:41:33,146 - openbb_app.core.utils - INFO - Successfully fetched quote data for 601857
2026-04-23 11:41:33,147 - openbb_app.core.utils - INFO - Fetching quote data for 601919
2026-04-23 11:41:33,152 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601919
2026-04-23 11:41:33,933 - openbb_app.core.utils - INFO - Successfully fetched quote data for 601919
2026-04-23 11:41:33,934 - openbb_app.core.utils - INFO - Fetching quote data for 601939
2026-04-23 11:41:33,939 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601939
2026-04-23 11:41:34,613 - openbb_app.core.utils - INFO - Successfully fetched quote data for 601939
2026-04-23 11:41:34,614 - openbb_app.core.utils - INFO - Fetching quote data for 601988
2026-04-23 11:41:34,621 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601988
2026-04-23 11:41:35,318 - openbb_app.core.utils - INFO - Successfully fetched quote data for 601988

[{'current_price': 0.0,
  'fifty_two_week_low': 67.5038,
  'fifty_two_week_high': 83.17,
  'dividend_yield': 5.05,
  'latest_dividend': 4.038,
  'symbol': '000333'},
 {'current_price': 0.0,
  'fifty_two_week_low': 5.27,
  'fifty_two_week_high': 8.11,
  'dividend_yield': 4.179,
  'latest_dividend': 0.229,
  'symbol': '600028'},
 {'current_price': 0.0,
  'fifty_two_week_low': 13.73,
  'fifty_two_week_high': 20.63,
  'dividend_yield': 0.628,
  'latest_dividend': 0.087,
  'symbol': '600104'},
 {'current_price': 0.0,
  'fifty_two_week_low': 3.35,
  'fifty_two_week_high': 5.74,
  'dividend_yield': 3.533,
  'latest_dividend': 0.124,
  'symbol': '600325'},
 {'current_price': 0.0,
  'fifty_two_week_low': 2.27,
  'fifty_two_week_high': 8.85,
  'dividend_yield': 0.0,
  'latest_dividend': 0.0,
  'symbol': '600376'},
 {'current_price': 0.0,
  'fifty_two_week_low': 4.5687,
  'fifty_two_week_high': 6.3327,
  'dividend_yield': 5.973,
  'latest_dividend': 0.31,
  'symbol': '600704'},
 {'current_price': 0.0,
  'fifty_two_week_low': 15.4727,
  'fifty_two_week_high': 21.54,
  'dividend_yield': 3.908,
  'latest_dividend': 0.8,
  'symbol': '600741'},
 {'current_price': 0.0,
  'fifty_two_week_low': 12.7,
  'fifty_two_week_high': 15.6762,
  'dividend_yield': 3.385,
  'latest_dividend': 0.457,
  'symbol': '600886'},
 {'current_price': 0.0,
  'fifty_two_week_low': 4.95,
  'fifty_two_week_high': 6.7278,
  'dividend_yield': 4.159,
  'latest_dividend': 0.22,
  'symbol': '601006'},
 {'current_price': 0.0,
  'fifty_two_week_low': 34.2626,
  'fifty_two_week_high': 50.38,
  'dividend_yield': 6.954,
  'latest_dividend': 3.24,
  'symbol': '601088'},
 {'current_price': 0.0,
  'fifty_two_week_low': 5.1524,
  'fifty_two_week_high': 8.5456,
  'dividend_yield': 3.465,
  'latest_dividend': 0.245,
  'symbol': '601288'},
 {'current_price': 0.0,
  'fifty_two_week_low': 6.8119,
  'fifty_two_week_high': 10.18,
  'dividend_yield': 2.637,
  'latest_dividend': 0.192,
  'symbol': '601319'},
 {'current_price': 0.0,
  'fifty_two_week_low': 6.48,
  'fifty_two_week_high': 8.1629,
  'dividend_yield': 4.613,
  'latest_dividend': 0.322,
  'symbol': '601328'},
 {'current_price': 0.0,
  'fifty_two_week_low': 6.6672,
  'fifty_two_week_high': 8.251,
  'dividend_yield': 4.042,
  'latest_dividend': 0.306,
  'symbol': '601398'},
 {'current_price': 0.0,
  'fifty_two_week_low': 4.87,
  'fifty_two_week_high': 6.2939,
  'dividend_yield': 4.181,
  'latest_dividend': 0.217,
  'symbol': '601658'},
 {'current_price': 0.0,
  'fifty_two_week_low': 5.59,
  'fifty_two_week_high': 7.7941,
  'dividend_yield': 4.567,
  'latest_dividend': 0.274,
  'symbol': '601728'},
 {'current_price': 0.0,
  'fifty_two_week_low': 7.4746,
  'fifty_two_week_high': 13.69,
  'dividend_yield': 4.034,
  'latest_dividend': 0.47,
  'symbol': '601857'},
 {'current_price': 0.0,
  'fifty_two_week_low': 12.7478,
  'fifty_two_week_high': 16.98,
  'dividend_yield': 11.159,
  'latest_dividend': 1.608,
  'symbol': '601919'},
 {'current_price': 0.0,
  'fifty_two_week_low': 8.3282,
  'fifty_two_week_high': 9.95,
  'dividend_yield': 3.924,
  'latest_dividend': 0.383,
  'symbol': '601939'},
 {'current_price': 0.0,
  'fifty_two_week_low': 5.0324,
  'fifty_two_week_high': 6.2684,
  'dividend_yield': 3.767,
  'latest_dividend': 0.22,
  'symbol': '601988'}]

In [5]:
from IPython.display import HTML, display
display(HTML(equity_data.get_screener(is_realized=True, market='HK')))

2026-04-23 11:41:39,856 - openbb_app.core.equity_data - INFO - Calling get_screener with is_realized=True, market=HK
2026-04-23 11:41:39,857 - openbb_app.core.equity_data - INFO - Using cached current prices with is_realized=True
2026-04-23 11:41:40,009 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 000333
2026-04-23 11:41:40,027 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,046 - openbb_akshare.models.equity_search - INFO - Searching for 000333 and found 1 results.
2026-04-23 11:41:40,050 - openbb_app.routes.portfolio - INFO - Found stock name for 000333: 美的集团
2026-04-23 11:41:40,051 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 600028
2026-04-23 11:41:40,066 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,082 - openbb_akshare.models.equity_search - INFO - Searching for 600028 and found 1 results.
2026-04-23 11:41:40,086 - openbb_app.routes.portfolio - INFO - Found stock name for 600028: 中国石化
2026-04-23 11:41:40,087 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 600104
2026-04-23 11:41:40,102 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,117 - openbb_akshare.models.equity_search - INFO - Searching for 600104 and found 1 results.
2026-04-23 11:41:40,121 - openbb_app.routes.portfolio - INFO - Found stock name for 600104: 上汽集团
2026-04-23 11:41:40,122 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 600325
2026-04-23 11:41:40,137 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,152 - openbb_akshare.models.equity_search - INFO - Searching for 600325 and found 1 results.
2026-04-23 11:41:40,156 - openbb_app.routes.portfolio - INFO - Found stock name for 600325: 华发股份
2026-04-23 11:41:40,156 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 600376
2026-04-23 11:41:40,171 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,187 - openbb_akshare.models.equity_search - INFO - Searching for 600376 and found 1 results.
2026-04-23 11:41:40,192 - openbb_app.routes.portfolio - INFO - Found stock name for 600376: 首开股份
2026-04-23 11:41:40,192 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 600704
2026-04-23 11:41:40,207 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,223 - openbb_akshare.models.equity_search - INFO - Searching for 600704 and found 1 results.
2026-04-23 11:41:40,226 - openbb_app.routes.portfolio - INFO - Found stock name for 600704: 物产中大
2026-04-23 11:41:40,227 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 600741
2026-04-23 11:41:40,242 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,258 - openbb_akshare.models.equity_search - INFO - Searching for 600741 and found 1 results.
2026-04-23 11:41:40,262 - openbb_app.routes.portfolio - INFO - Found stock name for 600741: 华域汽车
2026-04-23 11:41:40,263 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 600886
2026-04-23 11:41:40,281 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,295 - openbb_akshare.models.equity_search - INFO - Searching for 600886 and found 1 results.
2026-04-23 11:41:40,300 - openbb_app.routes.portfolio - INFO - Found stock name for 600886: 国投电力
2026-04-23 11:41:40,301 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 601006
2026-04-23 11:41:40,314 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,330 - openbb_akshare.models.equity_search - INFO - Searching for 601006 and found 1 results.
2026-04-23 11:41:40,334 - openbb_app.routes.portfolio - INFO - Found stock name for 601006: 大秦铁路
2026-04-23 11:41:40,335 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 601088
2026-04-23 11:41:40,349 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,364 - openbb_akshare.models.equity_search - INFO - Searching for 601088 and found 1 results.
2026-04-23 11:41:40,368 - openbb_app.routes.portfolio - INFO - Found stock name for 601088: 中国神华
2026-04-23 11:41:40,369 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 601288
2026-04-23 11:41:40,383 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,399 - openbb_akshare.models.equity_search - INFO - Searching for 601288 and found 1 results.
2026-04-23 11:41:40,403 - openbb_app.routes.portfolio - INFO - Found stock name for 601288: 农业银行
2026-04-23 11:41:40,404 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 601319
2026-04-23 11:41:40,418 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,434 - openbb_akshare.models.equity_search - INFO - Searching for 601319 and found 1 results.
2026-04-23 11:41:40,438 - openbb_app.routes.portfolio - INFO - Found stock name for 601319: 中国人保
2026-04-23 11:41:40,439 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 601328
2026-04-23 11:41:40,453 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,469 - openbb_akshare.models.equity_search - INFO - Searching for 601328 and found 1 results.
2026-04-23 11:41:40,473 - openbb_app.routes.portfolio - INFO - Found stock name for 601328: 交通银行
2026-04-23 11:41:40,474 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 601398
2026-04-23 11:41:40,489 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,503 - openbb_akshare.models.equity_search - INFO - Searching for 601398 and found 1 results.
2026-04-23 11:41:40,507 - openbb_app.routes.portfolio - INFO - Found stock name for 601398: 工商银行
2026-04-23 11:41:40,507 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 601658
2026-04-23 11:41:40,522 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,537 - openbb_akshare.models.equity_search - INFO - Searching for 601658 and found 1 results.
2026-04-23 11:41:40,541 - openbb_app.routes.portfolio - INFO - Found stock name for 601658: 邮储银行
2026-04-23 11:41:40,541 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 601728
2026-04-23 11:41:40,556 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,571 - openbb_akshare.models.equity_search - INFO - Searching for 601728 and found 1 results.
2026-04-23 11:41:40,574 - openbb_app.routes.portfolio - INFO - Found stock name for 601728: 中国电信
2026-04-23 11:41:40,575 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 601857
2026-04-23 11:41:40,590 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,606 - openbb_akshare.models.equity_search - INFO - Searching for 601857 and found 1 results.
2026-04-23 11:41:40,610 - openbb_app.routes.portfolio - INFO - Found stock name for 601857: 中国石油
2026-04-23 11:41:40,611 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 601919
2026-04-23 11:41:40,625 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,643 - openbb_akshare.models.equity_search - INFO - Searching for 601919 and found 1 results.
2026-04-23 11:41:40,646 - openbb_app.routes.portfolio - INFO - Found stock name for 601919: 中远海控
2026-04-23 11:41:40,647 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 601939
2026-04-23 11:41:40,661 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,677 - openbb_akshare.models.equity_search - INFO - Searching for 601939 and found 1 results.
2026-04-23 11:41:40,681 - openbb_app.routes.portfolio - INFO - Found stock name for 601939: 建设银行
2026-04-23 11:41:40,682 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 601988
2026-04-23 11:41:40,697 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-04-23 11:41:40,712 - openbb_akshare.models.equity_search - INFO - Searching for 601988 and found 1 results.
2026-04-23 11:41:40,715 - openbb_app.routes.portfolio - INFO - Found stock name for 601988: 中国银行

## 自选股

In [6]:
from openbb_app.routes.portfolio import get_all_stocks

get_all_stocks()

2026-04-23 11:42:19,624 - openbb_app.routes.portfolio - INFO - Using cache directory: C:\Users\roger\OpenBBUserData\cache
2026-04-23 11:42:19,624 - openbb_app.core.database - INFO - Creating directory for database: C:\Users\roger\OpenBBUserData\cache\appdata
2026-04-23 11:42:19,626 - openbb_app.core.database - INFO - Directory created successfully: C:\Users\roger\OpenBBUserData\cache\appdata
2026-04-23 11:42:19,630 - openbb_app.core.utils - INFO - Fetching quote data for 00144.HK
2026-04-23 11:42:19,636 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 00144
2026-04-23 11:42:20,380 - openbb_app.core.utils - INFO - Successfully fetched quote data for 00144.HK
2026-04-23 11:42:20,381 - openbb_app.core.utils - INFO - Fetching quote data for 01339.HK
2026-04-23 11:42:20,386 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 01339
2026-04-23 11:42:21,071 - openbb_app.core.utils - INFO - Successfully fetched quote data for 01339.HK
2026-04-23 11:42:21,072 - openbb_app.core.utils - INFO - Fetching quote data for 01398.HK
2026-04-23 11:42:21,079 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 01398
2026-04-23 11:42:21,786 - openbb_app.core.utils - INFO - Successfully fetched quote data for 01398.HK
2026-04-23 11:42:21,786 - openbb_app.core.utils - INFO - Fetching quote data for 600028.SH
2026-04-23 11:42:21,792 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600028
2026-04-23 11:42:22,530 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600028.SH
2026-04-23 11:42:22,530 - openbb_app.core.utils - INFO - Fetching quote data for 600036.SH
2026-04-23 11:42:22,535 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600036
2026-04-23 11:42:23,221 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600036.SH
2026-04-23 11:42:23,222 - openbb_app.core.utils - INFO - Fetching quote data for 600104.SH
2026-04-23 11:42:23,228 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600104
2026-04-23 11:42:24,002 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600104.SH
2026-04-23 11:42:24,003 - openbb_app.core.utils - INFO - Fetching quote data for 600325.SH
2026-04-23 11:42:24,008 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600325
2026-04-23 11:42:24,794 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600325.SH
2026-04-23 11:42:24,794 - openbb_app.core.utils - INFO - Fetching quote data for 601328.SH
2026-04-23 11:42:24,799 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601328
2026-04-23 11:42:25,500 - openbb_app.core.utils - INFO - Successfully fetched quote data for 601328.SH
2026-04-23 11:42:25,501 - openbb_app.core.utils - INFO - Fetching quote data for 601728.SH
2026-04-23 11:42:25,506 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601728
2026-04-23 11:42:26,221 - openbb_app.core.utils - INFO - Successfully fetched quote data for 601728.SH
2026-04-23 11:42:26,221 - openbb_app.core.utils - INFO - Fetching quote data for 601919.SH
2026-04-23 11:42:26,227 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601919
2026-04-23 11:42:27,007 - openbb_app.core.utils - INFO - Successfully fetched quote data for 601919.SH
2026-04-23 11:42:27,008 - openbb_app.core.utils - INFO - Fetching quote data for 920571.BJ
2026-04-23 11:42:27,014 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: BJ920571
2026-04-23 11:42:27,773 - openbb_app.core.utils - INFO - Successfully fetched quote data for 920571.BJ
2026-04-23 11:42:27,773 - openbb_app.core.utils - INFO - Fetching quote data for 920809.BJ
2026-04-23 11:42:27,779 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: BJ920809
2026-04-23 11:42:28,547 - openbb_app.core.utils - INFO - Successfully fetched quote data for 920809.BJ

[{'symbol': '00144.HK',
  'name': '招商局港口',
  'avg_cost': 0.0,
  'quantity': 0,
  'total_value': 0.0,
  'current_price': 0.0,
  'fifty_two_week_low': 12.06,
  'fifty_two_week_high': 17.85,
  'dividend_yield': 5.65,
  'latest_dividend': 0.886,
  'strategy': '买入',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=HKEX:144'},
 {'symbol': '01339.HK',
  'name': '中国人民保险集团',
  'avg_cost': 5.9037,
  'quantity': 10000,
  'total_value': 59037.0,
  'current_price': 0.0,
  'fifty_two_week_low': 4.28,
  'fifty_two_week_high': 7.63,
  'dividend_yield': 4.12,
  'latest_dividend': 0.22,
  'strategy': '买入',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=HKEX:1339'},
 {'symbol': '01398.HK',
  'name': '工商银行',
  'avg_cost': 6.5049,
  'quantity': 10000,
  'total_value': 65049.0,
  'current_price': 0.0,
  'fifty_two_week_low': 5.15,
  'fifty_two_week_high': 7.31,
  'dividend_yield': 4.87,
  'latest_dividend': 0.351,
  'strategy': '买入',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=HKEX:1398'},
 {'symbol': '600028.SH',
  'name': '中国石化',
  'avg_cost': 6.04185,
  'quantity': 10000,
  'total_value': 60418.5,
  'current_price': 0.0,
  'fifty_two_week_low': 5.27,
  'fifty_two_week_high': 8.11,
  'dividend_yield': 4.179,
  'latest_dividend': 0.229,
  'strategy': '买入',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600028'},
 {'symbol': '600036.SH',
  'name': '招商银行',
  'avg_cost': 40.037,
  'quantity': 0,
  'total_value': 0.0,
  'current_price': 0.0,
  'fifty_two_week_low': 37.31,
  'fifty_two_week_high': 45.3618,
  'dividend_yield': 7.605,
  'latest_dividend': 3.013,
  'strategy': '买入',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600036'},
 {'symbol': '600104.SH',
  'name': '上汽集团',
  'avg_cost': 0.0,
  'quantity': 0,
  'total_value': 0.0,
  'current_price': 0.0,
  'fifty_two_week_low': 13.73,
  'fifty_two_week_high': 20.63,
  'dividend_yield': 0.628,
  'latest_dividend': 0.087,
  'strategy': '买入',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600104'},
 {'symbol': '600325.SH',
  'name': '华发股份',
  'avg_cost': 0.0,
  'quantity': 0,
  'total_value': 0.0,
  'current_price': 0.0,
  'fifty_two_week_low': 3.35,
  'fifty_two_week_high': 5.74,
  'dividend_yield': 3.533,
  'latest_dividend': 0.124,
  'strategy': '买入',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600325'},
 {'symbol': '601328.SH',
  'name': '交通银行',
  'avg_cost': 6.9079,
  'quantity': 10000,
  'total_value': 69079.0,
  'current_price': 0.0,
  'fifty_two_week_low': 6.48,
  'fifty_two_week_high': 8.1629,
  'dividend_yield': 4.613,
  'latest_dividend': 0.322,
  'strategy': '买入',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:601328'},
 {'symbol': '601728.SH',
  'name': '中国电信',
  'avg_cost': 0.0,
  'quantity': 0,
  'total_value': 0.0,
  'current_price': 0.0,
  'fifty_two_week_low': 5.59,
  'fifty_two_week_high': 7.7941,
  'dividend_yield': 4.567,
  'latest_dividend': 0.274,
  'strategy': '买入',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:601728'},
 {'symbol': '601919.SH',
  'name': '中远海控',
  'avg_cost': 15.8327,
  'quantity': 10000,
  'total_value': 158327.0,
  'current_price': 0.0,
  'fifty_two_week_low': 12.7478,
  'fifty_two_week_high': 16.98,
  'dividend_yield': 11.159,
  'latest_dividend': 1.608,
  'strategy': '买入',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:601919'},
 {'symbol': '920571.BJ',
  'name': '国航远洋',
  'avg_cost': 1.1235,
  'quantity': 10000,
  'total_value': 11235.0,
  'current_price': 0.0,
  'fifty_two_week_low': 6.0787,
  'fifty_two_week_high': 16.7115,
  'dividend_yield': 0.941,
  'latest_dividend': 0.1,
  'strategy': '买入',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=BSE:920571'},
 {'symbol': '920809.BJ',
  'name': '安达科技',
  'avg_cost': 0.0,
  'quantity': 0,
  'total_value': 0.0,
  'current_price': 0.0,
  'fifty_two_week_low': 5.1,
  'fifty_two_week_high': 9.68,
  'dividend_yield': 0.0,
  'latest_dividend': 0.0,
  'strategy': '买入',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=BSE:920809'}]

In [2]:
from openbb_app.routes.portfolio import get_db_manager
db_manager = get_db_manager()

2026-03-20 15:53:28,343 - openbb_app.routes.portfolio - INFO - Using cache directory: C:\Users\roger\OpenBBUserData\cache
2026-03-20 15:53:28,343 - openbb_app.core.database - INFO - Creating directory for database: C:\Users\roger\OpenBBUserData\cache\appdata
2026-03-20 15:53:28,343 - openbb_app.core.database - INFO - Directory created successfully: C:\Users\roger\OpenBBUserData\cache\appdata

In [3]:
db_manager.get_all_portfolio_stocks()

2026-03-20 15:53:31,006 - openbb_app.core.utils - INFO - Fetching quote data for 600028.SH
2026-03-20 15:53:31,021 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600028
2026-03-20 15:53:31,918 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600028.SH
2026-03-20 15:53:31,920 - openbb_app.core.utils - INFO - Fetching quote data for 600325.SH
2026-03-20 15:53:31,925 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600325
2026-03-20 15:53:32,759 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600325.SH

[{'symbol': '600028.SH',
  'name': '中国石化',
  'avg_cost': 0.0,
  'quantity': 0,
  'total_value': 0.0,
  'current_price': 6.08,
  'fifty_two_week_low': 5.0466,
  'fifty_two_week_high': 8.11,
  'dividend_yield': 3.766,
  'latest_dividend': 0.229,
  'strategy': '持有',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600028'},
 {'symbol': '600325.SH',
  'name': '华发股份',
  'avg_cost': 0.0,
  'quantity': 0,
  'total_value': 0.0,
  'current_price': 3.85,
  'fifty_two_week_low': 3.85,
  'fifty_two_week_high': 5.74,
  'dividend_yield': 3.221,
  'latest_dividend': 0.124,
  'strategy': '买进',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600325'}]

In [4]:
db_manager.get_portfolio_stock("600325.SH")

2026-03-20 15:53:36,226 - openbb_app.core.utils - INFO - Fetching quote data for 600325.SH
2026-03-20 15:53:36,231 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600325
2026-03-20 15:53:37,124 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600325.SH

{'symbol': '600325.SH',
 'name': '华发股份',
 'avg_cost': 0.0,
 'quantity': 0,
 'total_value': 0.0,
 'current_price': 3.85,
 'fifty_two_week_low': 3.85,
 'fifty_two_week_high': 5.74,
 'dividend_yield': 3.221,
 'latest_dividend': 0.124,
 'strategy': '买进',
 'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600325'}

# Others

In [ ]:
from openbb import obb
from openbb_core.app.service.user_service import UserService
 
# 方式1：通过 UserService 修改
user_service = UserService()
user_settings = user_service.read_from_file()
default_provider = "tdxquant"
 
# 设置某个路由的默认提供者
user_settings.defaults.commands.update({
    "equity.price.historical": {
        "provider": default_provider
    },
    "equity.price.quote": {
        "provider": default_provider
    },
    "equity.search": {
        "provider": default_provider
    },
    "equity.fundamental.metrics": {
        "provider": default_provider
    },
    "obb.equity.profile": {
        "provider": default_provider
    }
})
 
# 保存到文件
UserService.write_to_file(user_settings)

In [ ]:
obb.user.credentials.tushare_api_key="dummy_key"
from openbb_core.app.service.user_service import UserService
u = UserService.read_from_file()
u.credentials.tushare_api_key="dummy_key"
UserService.write_to_file(u)

In [ ]:
from openbb_core.app.service.user_service import UserService
from pathlib import Path
 
# 读取用户设置
settings = UserService.read_from_file()
cache_dir = Path(settings.preferences.cache_directory)
 
# 在数据目录下创建SQLite数据库
db_path = cache_dir / "appdata/equity.db"
#conn = sqlite3.connect(db_path)